live_config_reload = true

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[scrolling]
history = 100000

[window]
dynamic_title = true

[window.padding]
x = 4
y = 0
